services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./api.env
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`sdapi.${DOMAIN}`)
      traefik.http.services.api.loadbalancer.server.port: 8000
    networks:
      - mia
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_BASE_PATH=${VITE_API_BASE_PATH}
        - VITE_API_AUTH_PATH=${VITE_API_AUTH_PATH}
    environment:
      - NODE_ENV=production
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`sd.${DOMAIN}`)
      traefik.http.services.web.loadbalancer.server.port: 3000
    networks:
      - mia
    depends_on:
      - api

networks:
  mia:
    external: true