/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MeReservationsRouteImport } from './routes/me.reservations'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as RestaurantsRestaurantIdIndexRouteImport } from './routes/restaurants.$restaurantId.index'
import { Route as RestaurantsRestaurantIdAdminRouteImport } from './routes/restaurants.$restaurantId.admin'
import { Route as RestaurantsRestaurantIdReservationIndexRouteImport } from './routes/restaurants.$restaurantId.reservation.index'
import { Route as RestaurantsRestaurantIdKioskIndexRouteImport } from './routes/restaurants.$restaurantId.kiosk.index'
import { Route as RestaurantsRestaurantIdCashierIndexRouteImport } from './routes/restaurants.$restaurantId.cashier.index'
import { Route as RestaurantsRestaurantIdAdminIndexRouteImport } from './routes/restaurants.$restaurantId.admin.index'
import { Route as RestaurantsRestaurantIdAdminStaffRouteImport } from './routes/restaurants.$restaurantId.admin.staff'
import { Route as RestaurantsRestaurantIdAdminReservationsRouteImport } from './routes/restaurants.$restaurantId.admin.reservations'
import { Route as RestaurantsRestaurantIdAdminOrdersRouteImport } from './routes/restaurants.$restaurantId.admin.orders'
import { Route as RestaurantsRestaurantIdAdminOpeningHoursRouteImport } from './routes/restaurants.$restaurantId.admin.opening-hours'
import { Route as RestaurantsRestaurantIdAdminMenuRouteImport } from './routes/restaurants.$restaurantId.admin.menu'
import { Route as RestaurantsRestaurantIdAdminFloorPlanRouteImport } from './routes/restaurants.$restaurantId.admin.floor-plan'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MeReservationsRoute = MeReservationsRouteImport.update({
  id: '/me/reservations',
  path: '/me/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const RestaurantsRestaurantIdIndexRoute =
  RestaurantsRestaurantIdIndexRouteImport.update({
    id: '/restaurants/$restaurantId/',
    path: '/restaurants/$restaurantId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsRestaurantIdAdminRoute =
  RestaurantsRestaurantIdAdminRouteImport.update({
    id: '/restaurants/$restaurantId/admin',
    path: '/restaurants/$restaurantId/admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsRestaurantIdReservationIndexRoute =
  RestaurantsRestaurantIdReservationIndexRouteImport.update({
    id: '/restaurants/$restaurantId/reservation/',
    path: '/restaurants/$restaurantId/reservation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsRestaurantIdKioskIndexRoute =
  RestaurantsRestaurantIdKioskIndexRouteImport.update({
    id: '/restaurants/$restaurantId/kiosk/',
    path: '/restaurants/$restaurantId/kiosk/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsRestaurantIdCashierIndexRoute =
  RestaurantsRestaurantIdCashierIndexRouteImport.update({
    id: '/restaurants/$restaurantId/cashier/',
    path: '/restaurants/$restaurantId/cashier/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantsRestaurantIdAdminIndexRoute =
  RestaurantsRestaurantIdAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)
const RestaurantsRestaurantIdAdminStaffRoute =
  RestaurantsRestaurantIdAdminStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)
const RestaurantsRestaurantIdAdminReservationsRoute =
  RestaurantsRestaurantIdAdminReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)
const RestaurantsRestaurantIdAdminOrdersRoute =
  RestaurantsRestaurantIdAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)
const RestaurantsRestaurantIdAdminOpeningHoursRoute =
  RestaurantsRestaurantIdAdminOpeningHoursRouteImport.update({
    id: '/opening-hours',
    path: '/opening-hours',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)
const RestaurantsRestaurantIdAdminMenuRoute =
  RestaurantsRestaurantIdAdminMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)
const RestaurantsRestaurantIdAdminFloorPlanRoute =
  RestaurantsRestaurantIdAdminFloorPlanRouteImport.update({
    id: '/floor-plan',
    path: '/floor-plan',
    getParentRoute: () => RestaurantsRestaurantIdAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/me/reservations': typeof MeReservationsRoute
  '/admin/': typeof AdminIndexRoute
  '/restaurants/$restaurantId/admin': typeof RestaurantsRestaurantIdAdminRouteWithChildren
  '/restaurants/$restaurantId/': typeof RestaurantsRestaurantIdIndexRoute
  '/restaurants/$restaurantId/admin/floor-plan': typeof RestaurantsRestaurantIdAdminFloorPlanRoute
  '/restaurants/$restaurantId/admin/menu': typeof RestaurantsRestaurantIdAdminMenuRoute
  '/restaurants/$restaurantId/admin/opening-hours': typeof RestaurantsRestaurantIdAdminOpeningHoursRoute
  '/restaurants/$restaurantId/admin/orders': typeof RestaurantsRestaurantIdAdminOrdersRoute
  '/restaurants/$restaurantId/admin/reservations': typeof RestaurantsRestaurantIdAdminReservationsRoute
  '/restaurants/$restaurantId/admin/staff': typeof RestaurantsRestaurantIdAdminStaffRoute
  '/restaurants/$restaurantId/admin/': typeof RestaurantsRestaurantIdAdminIndexRoute
  '/restaurants/$restaurantId/cashier/': typeof RestaurantsRestaurantIdCashierIndexRoute
  '/restaurants/$restaurantId/kiosk/': typeof RestaurantsRestaurantIdKioskIndexRoute
  '/restaurants/$restaurantId/reservation/': typeof RestaurantsRestaurantIdReservationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/me/reservations': typeof MeReservationsRoute
  '/admin': typeof AdminIndexRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdIndexRoute
  '/restaurants/$restaurantId/admin/floor-plan': typeof RestaurantsRestaurantIdAdminFloorPlanRoute
  '/restaurants/$restaurantId/admin/menu': typeof RestaurantsRestaurantIdAdminMenuRoute
  '/restaurants/$restaurantId/admin/opening-hours': typeof RestaurantsRestaurantIdAdminOpeningHoursRoute
  '/restaurants/$restaurantId/admin/orders': typeof RestaurantsRestaurantIdAdminOrdersRoute
  '/restaurants/$restaurantId/admin/reservations': typeof RestaurantsRestaurantIdAdminReservationsRoute
  '/restaurants/$restaurantId/admin/staff': typeof RestaurantsRestaurantIdAdminStaffRoute
  '/restaurants/$restaurantId/admin': typeof RestaurantsRestaurantIdAdminIndexRoute
  '/restaurants/$restaurantId/cashier': typeof RestaurantsRestaurantIdCashierIndexRoute
  '/restaurants/$restaurantId/kiosk': typeof RestaurantsRestaurantIdKioskIndexRoute
  '/restaurants/$restaurantId/reservation': typeof RestaurantsRestaurantIdReservationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/me/reservations': typeof MeReservationsRoute
  '/admin/': typeof AdminIndexRoute
  '/restaurants/$restaurantId/admin': typeof RestaurantsRestaurantIdAdminRouteWithChildren
  '/restaurants/$restaurantId/': typeof RestaurantsRestaurantIdIndexRoute
  '/restaurants/$restaurantId/admin/floor-plan': typeof RestaurantsRestaurantIdAdminFloorPlanRoute
  '/restaurants/$restaurantId/admin/menu': typeof RestaurantsRestaurantIdAdminMenuRoute
  '/restaurants/$restaurantId/admin/opening-hours': typeof RestaurantsRestaurantIdAdminOpeningHoursRoute
  '/restaurants/$restaurantId/admin/orders': typeof RestaurantsRestaurantIdAdminOrdersRoute
  '/restaurants/$restaurantId/admin/reservations': typeof RestaurantsRestaurantIdAdminReservationsRoute
  '/restaurants/$restaurantId/admin/staff': typeof RestaurantsRestaurantIdAdminStaffRoute
  '/restaurants/$restaurantId/admin/': typeof RestaurantsRestaurantIdAdminIndexRoute
  '/restaurants/$restaurantId/cashier/': typeof RestaurantsRestaurantIdCashierIndexRoute
  '/restaurants/$restaurantId/kiosk/': typeof RestaurantsRestaurantIdKioskIndexRoute
  '/restaurants/$restaurantId/reservation/': typeof RestaurantsRestaurantIdReservationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/workspace'
    | '/admin/restaurants'
    | '/admin/users'
    | '/me/reservations'
    | '/admin/'
    | '/restaurants/$restaurantId/admin'
    | '/restaurants/$restaurantId/'
    | '/restaurants/$restaurantId/admin/floor-plan'
    | '/restaurants/$restaurantId/admin/menu'
    | '/restaurants/$restaurantId/admin/opening-hours'
    | '/restaurants/$restaurantId/admin/orders'
    | '/restaurants/$restaurantId/admin/reservations'
    | '/restaurants/$restaurantId/admin/staff'
    | '/restaurants/$restaurantId/admin/'
    | '/restaurants/$restaurantId/cashier/'
    | '/restaurants/$restaurantId/kiosk/'
    | '/restaurants/$restaurantId/reservation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/workspace'
    | '/admin/restaurants'
    | '/admin/users'
    | '/me/reservations'
    | '/admin'
    | '/restaurants/$restaurantId'
    | '/restaurants/$restaurantId/admin/floor-plan'
    | '/restaurants/$restaurantId/admin/menu'
    | '/restaurants/$restaurantId/admin/opening-hours'
    | '/restaurants/$restaurantId/admin/orders'
    | '/restaurants/$restaurantId/admin/reservations'
    | '/restaurants/$restaurantId/admin/staff'
    | '/restaurants/$restaurantId/admin'
    | '/restaurants/$restaurantId/cashier'
    | '/restaurants/$restaurantId/kiosk'
    | '/restaurants/$restaurantId/reservation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/workspace'
    | '/admin/restaurants'
    | '/admin/users'
    | '/me/reservations'
    | '/admin/'
    | '/restaurants/$restaurantId/admin'
    | '/restaurants/$restaurantId/'
    | '/restaurants/$restaurantId/admin/floor-plan'
    | '/restaurants/$restaurantId/admin/menu'
    | '/restaurants/$restaurantId/admin/opening-hours'
    | '/restaurants/$restaurantId/admin/orders'
    | '/restaurants/$restaurantId/admin/reservations'
    | '/restaurants/$restaurantId/admin/staff'
    | '/restaurants/$restaurantId/admin/'
    | '/restaurants/$restaurantId/cashier/'
    | '/restaurants/$restaurantId/kiosk/'
    | '/restaurants/$restaurantId/reservation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WorkspaceRoute: typeof WorkspaceRoute
  MeReservationsRoute: typeof MeReservationsRoute
  RestaurantsRestaurantIdAdminRoute: typeof RestaurantsRestaurantIdAdminRouteWithChildren
  RestaurantsRestaurantIdIndexRoute: typeof RestaurantsRestaurantIdIndexRoute
  RestaurantsRestaurantIdCashierIndexRoute: typeof RestaurantsRestaurantIdCashierIndexRoute
  RestaurantsRestaurantIdKioskIndexRoute: typeof RestaurantsRestaurantIdKioskIndexRoute
  RestaurantsRestaurantIdReservationIndexRoute: typeof RestaurantsRestaurantIdReservationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/me/reservations': {
      id: '/me/reservations'
      path: '/me/reservations'
      fullPath: '/me/reservations'
      preLoaderRoute: typeof MeReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurants/$restaurantId/': {
      id: '/restaurants/$restaurantId/'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId/'
      preLoaderRoute: typeof RestaurantsRestaurantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/admin': {
      id: '/restaurants/$restaurantId/admin'
      path: '/restaurants/$restaurantId/admin'
      fullPath: '/restaurants/$restaurantId/admin'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/reservation/': {
      id: '/restaurants/$restaurantId/reservation/'
      path: '/restaurants/$restaurantId/reservation'
      fullPath: '/restaurants/$restaurantId/reservation/'
      preLoaderRoute: typeof RestaurantsRestaurantIdReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/kiosk/': {
      id: '/restaurants/$restaurantId/kiosk/'
      path: '/restaurants/$restaurantId/kiosk'
      fullPath: '/restaurants/$restaurantId/kiosk/'
      preLoaderRoute: typeof RestaurantsRestaurantIdKioskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/cashier/': {
      id: '/restaurants/$restaurantId/cashier/'
      path: '/restaurants/$restaurantId/cashier'
      fullPath: '/restaurants/$restaurantId/cashier/'
      preLoaderRoute: typeof RestaurantsRestaurantIdCashierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId/admin/': {
      id: '/restaurants/$restaurantId/admin/'
      path: '/'
      fullPath: '/restaurants/$restaurantId/admin/'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminIndexRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
    '/restaurants/$restaurantId/admin/staff': {
      id: '/restaurants/$restaurantId/admin/staff'
      path: '/staff'
      fullPath: '/restaurants/$restaurantId/admin/staff'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminStaffRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
    '/restaurants/$restaurantId/admin/reservations': {
      id: '/restaurants/$restaurantId/admin/reservations'
      path: '/reservations'
      fullPath: '/restaurants/$restaurantId/admin/reservations'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminReservationsRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
    '/restaurants/$restaurantId/admin/orders': {
      id: '/restaurants/$restaurantId/admin/orders'
      path: '/orders'
      fullPath: '/restaurants/$restaurantId/admin/orders'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminOrdersRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
    '/restaurants/$restaurantId/admin/opening-hours': {
      id: '/restaurants/$restaurantId/admin/opening-hours'
      path: '/opening-hours'
      fullPath: '/restaurants/$restaurantId/admin/opening-hours'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminOpeningHoursRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
    '/restaurants/$restaurantId/admin/menu': {
      id: '/restaurants/$restaurantId/admin/menu'
      path: '/menu'
      fullPath: '/restaurants/$restaurantId/admin/menu'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminMenuRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
    '/restaurants/$restaurantId/admin/floor-plan': {
      id: '/restaurants/$restaurantId/admin/floor-plan'
      path: '/floor-plan'
      fullPath: '/restaurants/$restaurantId/admin/floor-plan'
      preLoaderRoute: typeof RestaurantsRestaurantIdAdminFloorPlanRouteImport
      parentRoute: typeof RestaurantsRestaurantIdAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RestaurantsRestaurantIdAdminRouteChildren {
  RestaurantsRestaurantIdAdminFloorPlanRoute: typeof RestaurantsRestaurantIdAdminFloorPlanRoute
  RestaurantsRestaurantIdAdminMenuRoute: typeof RestaurantsRestaurantIdAdminMenuRoute
  RestaurantsRestaurantIdAdminOpeningHoursRoute: typeof RestaurantsRestaurantIdAdminOpeningHoursRoute
  RestaurantsRestaurantIdAdminOrdersRoute: typeof RestaurantsRestaurantIdAdminOrdersRoute
  RestaurantsRestaurantIdAdminReservationsRoute: typeof RestaurantsRestaurantIdAdminReservationsRoute
  RestaurantsRestaurantIdAdminStaffRoute: typeof RestaurantsRestaurantIdAdminStaffRoute
  RestaurantsRestaurantIdAdminIndexRoute: typeof RestaurantsRestaurantIdAdminIndexRoute
}

const RestaurantsRestaurantIdAdminRouteChildren: RestaurantsRestaurantIdAdminRouteChildren =
  {
    RestaurantsRestaurantIdAdminFloorPlanRoute:
      RestaurantsRestaurantIdAdminFloorPlanRoute,
    RestaurantsRestaurantIdAdminMenuRoute:
      RestaurantsRestaurantIdAdminMenuRoute,
    RestaurantsRestaurantIdAdminOpeningHoursRoute:
      RestaurantsRestaurantIdAdminOpeningHoursRoute,
    RestaurantsRestaurantIdAdminOrdersRoute:
      RestaurantsRestaurantIdAdminOrdersRoute,
    RestaurantsRestaurantIdAdminReservationsRoute:
      RestaurantsRestaurantIdAdminReservationsRoute,
    RestaurantsRestaurantIdAdminStaffRoute:
      RestaurantsRestaurantIdAdminStaffRoute,
    RestaurantsRestaurantIdAdminIndexRoute:
      RestaurantsRestaurantIdAdminIndexRoute,
  }

const RestaurantsRestaurantIdAdminRouteWithChildren =
  RestaurantsRestaurantIdAdminRoute._addFileChildren(
    RestaurantsRestaurantIdAdminRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WorkspaceRoute: WorkspaceRoute,
  MeReservationsRoute: MeReservationsRoute,
  RestaurantsRestaurantIdAdminRoute:
    RestaurantsRestaurantIdAdminRouteWithChildren,
  RestaurantsRestaurantIdIndexRoute: RestaurantsRestaurantIdIndexRoute,
  RestaurantsRestaurantIdCashierIndexRoute:
    RestaurantsRestaurantIdCashierIndexRoute,
  RestaurantsRestaurantIdKioskIndexRoute:
    RestaurantsRestaurantIdKioskIndexRoute,
  RestaurantsRestaurantIdReservationIndexRoute:
    RestaurantsRestaurantIdReservationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
